import React from 'react';
import { MessageSquare, Heart, Share2, Users } from 'lucide-react';

const CommunityPreview = () => {
  const posts = [
    {
      id: 1,
      author: 'Sneha Patil',
      avatar: '👩‍🦰',
      time: '2 hours ago',
      content: 'Just smashed my 10k running session today! Feel super energized! Who is up for a group run this Sunday?',
      likes: 12,
      replies: 4
    },
    {
      id: 2,
      author: 'Rohan Sharma',
      avatar: '👨',
      time: '4 hours ago',
      content: 'Sticking to the high-protein diet planner generated by Co-Pilot. Seeing great strength recovery results.',
      likes: 8,
      replies: 2
    }
  ];

  return (
    <div className="bg-white/70 dark:bg-gray-800/80 backdrop-blur-xl border border-gray-100 dark:border-gray-700 p-6 rounded-3xl shadow-xl h-full animate-fade-in flex flex-col justify-between">
      <div>
        <div className="flex items-center gap-3 pb-4 border-b border-gray-100 dark:border-gray-700 mb-6">
          <div className="p-3 bg-theme-gradient text-white rounded-2xl shadow-md">
            <Users className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-extrabold text-2xl text-gray-800 dark:text-gray-100">Community Preview</h3>
            <p className="text-xs text-gray-500 dark:text-gray-400">Join the discussion on the wellness boards</p>
          </div>
        </div>

        <div className="space-y-4">
          {posts.map((post) => (
            <div 
              key={post.id}
              className="p-4 bg-gray-50/50 dark:bg-gray-750/30 border border-gray-100/50 dark:border-gray-700/50 rounded-2xl space-y-3"
            >
              <div className="flex justify-between items-center">
                <div className="flex gap-2.5 items-center">
                  <div className="w-9 h-9 rounded-full bg-white dark:bg-gray-700 flex items-center justify-center text-lg border">
                    {post.avatar}
                  </div>
                  <div>
                    <h4 className="text-xs font-black text-gray-850 dark:text-gray-100">{post.author}</h4>
                    <p className="text-[9px] text-gray-400 font-semibold">{post.time}</p>
                  </div>
                </div>
              </div>

              <p className="text-xs text-gray-600 dark:text-gray-300 leading-relaxed font-semibold">
                {post.content}
              </p>

              {/* Feed Actions */}
              <div className="flex gap-4 text-gray-400 pt-2 text-[10px] font-black tracking-wider border-t border-gray-100/50 dark:border-gray-700/50">
                <button className="flex items-center gap-1 hover:text-rose-500 transition-colors">
                  <Heart className="w-3.5 h-3.5" /> {post.likes}
                </button>
                <button className="flex items-center gap-1 hover:text-accent-primary transition-colors">
                  <MessageSquare className="w-3.5 h-3.5" /> {post.replies}
                </button>
                <button className="flex items-center gap-1 hover:text-blue-500 transition-colors">
                  <Share2 className="w-3.5 h-3.5" /> Share
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
      
    </div>
  );
};

export default CommunityPreview;
