import axios from 'axios';
import User from '../models/User.js';
import Entry from '../models/Entry.js';
import Tracker from '../models/Tracker.js';

// General helper to call Gemini
const callGemini = async (prompt, isJson = false) => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === 'YOUR_GEMINI_API_KEY') {
    console.warn('GEMINI_API_KEY is not defined. Falling back to mock AI responses.');
    return getFallbackResponse(prompt, isJson);
  }

  try {
    const payload = {
      contents: [{ parts: [{ text: prompt }] }]
    };
    if (isJson) {
      payload.generationConfig = {
        responseMimeType: "application/json"
      };
    }

    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      payload,
      { headers: { 'Content-Type': 'application/json' } }
    );

    const resultText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!resultText) throw new Error('Empty response from Gemini API');
    return isJson ? JSON.parse(resultText) : resultText;
  } catch (error) {
    console.error('Gemini API Error:', error.message);
    return getFallbackResponse(prompt, isJson);
  }
};

// Resilient mocks if API Key is not set or fails
const getFallbackResponse = (prompt, isJson) => {
  if (isJson) {
    if (prompt.toLowerCase().includes('diet')) {
      return {
        dailyCaloriesTarget: 2200,
        macroSplit: { carbs: "50%", protein: "25%", fat: "25%" },
        meals: [
          { name: "Breakfast", options: ["Oatmeal with almonds & banana", "Scrambled egg whites with avocado toast"], waterMl: 300 },
          { name: "Lunch", options: ["Grilled chicken breast salad with quinoa", "Brown rice with mixed beans & broccoli"], waterMl: 400 },
          { name: "Snack", options: ["Greek yogurt with honey", "A handful of mixed walnuts and berries"], waterMl: 250 },
          { name: "Dinner", options: ["Baked salmon with asparagus & sweet potato", "Lentil soup with side garden salad"], waterMl: 400 }
        ],
        tips: ["Drink at least 2.5L of water daily.", "Avoid processed sugars.", "Eat slowly and practice portion control."]
      };
    } else {
      // Workout plan fallback
      return {
        weeklyFrequency: 3,
        routine: [
          { day: "Day 1 - Push", exercises: ["Incline dumbbell press (3x10)", "Dumbbell shoulder press (3x12)", "Tricep overhead extensions (3x12)"], durationMin: 45 },
          { day: "Day 2 - Pull", exercises: ["Pull-ups or lat pulldowns (3x8)", "Dumbbell rows (3x10)", "Hammer curls (3x12)"], durationMin: 45 },
          { day: "Day 3 - Legs & Core", exercises: ["Squats or goblet squats (3x12)", "Romanian deadlifts (3x10)", "Plank hold (3x60s)"], durationMin: 50 }
        ],
        tips: ["Warm up with 5-10 mins cardio first.", "Focus on correct posture before adding weights.", "Rest 60-90s between exercise sets."]
      };
    }
  }

  // Text response fallback
  if (prompt.toLowerCase().includes('weekly report')) {
    return `### HealthTrack Weekly Wellness Analysis (Demo Mode)

Your logged statistics have been analyzed for the past week:
- **Calorie Intake**: Good consistency, averaging ~2,100 kcal daily.
- **Activity**: Active workouts completed 3 times. Excellent cardiorespiratory logging!
- **Sleep Quality**: Moderate. Average hours slept: 6.8 hrs. We recommend aiming for 7.5+ hours to improve recovery.
- **Hydration**: Slightly low. Average intake: 1,600 ml/day. Try setting a water logging goal of 2,500 ml.

*Disclaimer: This report is automatically generated by HealthTrack AI to assist your wellness journey. It does not replace medical diagnostics.*`;
  }

  return "Hello! I am your AI Health Assistant. I am here to help answer wellness questions, design meal guides, or structure workout schedules. (Note: Running in demo mode. Please query me about diet, workouts, or general health tips!). \n\n*Disclaimer: I am an AI, not a medical practitioner. For physical symptoms, please consult a certified doctor.*";
};

// Endpoints
export const chatAssistant = async (req, res) => {
  try {
    const { message, history } = req.body;
    if (!message) return res.status(400).json({ message: 'Message is required' });

    const systemPrompt = `You are a professional, empathetic, and knowledgeable AI Health Assistant on the HealthTrack platform. 
Your goal is to guide users towards healthier choices by answering wellness questions, suggesting habits, and offering fitness/diet tips.
Always maintain a helpful and professional tone.
CRITICAL: Include a brief medical disclaimer at the bottom of your response stating that you are an AI assistant and not a medical doctor, and users should consult a physician for urgent health questions.

User history context (if any): ${JSON.stringify(history || [])}
User query: ${message}
Response:`;

    const reply = await callGemini(systemPrompt, false);
    res.json({ reply });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

export const generateDietPlan = async (req, res) => {
  try {
    const user = await User.findById(req.user._id);
    if (!user) return res.status(404).json({ message: 'User not found' });

    const { preferences, healthGoals } = req.body;

    const systemPrompt = `Generate a customized daily diet plan in JSON format based on the following user profile:
Age: ${user.age || 'Not specified'}
Gender: ${user.gender || 'Not specified'}
Height: ${user.heightCm || 'Not specified'} cm
Weight: ${user.weightKg || 'Not specified'} kg
Activity Level: ${user.activityLevel || 'Not specified'}
Dietary Preferences: ${preferences || 'None'}
Health Goals: ${healthGoals || 'Maintain health'}

Output MUST be a valid JSON object matching the following structure:
{
  "dailyCaloriesTarget": number,
  "macroSplit": { "carbs": string, "protein": string, "fat": string },
  "meals": [
    { "name": string, "options": [string], "waterMl": number }
  ],
  "tips": [string]
}
Do not return any other text, markdown blocks, or formatting, just return raw JSON.`;

    const dietPlan = await callGemini(systemPrompt, true);
    res.json(dietPlan);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

export const generateWorkoutPlan = async (req, res) => {
  try {
    const user = await User.findById(req.user._id);
    if (!user) return res.status(404).json({ message: 'User not found' });

    const { fitnessLevel, goals } = req.body;

    const systemPrompt = `Generate a customized weekly workout routine in JSON format based on the following user profile:
Age: ${user.age || 'Not specified'}
Gender: ${user.gender || 'Not specified'}
Weight: ${user.weightKg || 'Not specified'} kg
Fitness Level: ${fitnessLevel || 'Beginner'}
Goals: ${goals || 'Improve stamina'}

Output MUST be a valid JSON object matching the following structure:
{
  "weeklyFrequency": number,
  "routine": [
    { "day": string, "exercises": [string], "durationMin": number }
  ],
  "tips": [string]
}
Do not return any other text, markdown blocks, or formatting, just return raw JSON.`;

    const workoutPlan = await callGemini(systemPrompt, true);
    res.json(workoutPlan);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

export const generateWeeklyReport = async (req, res) => {
  try {
    const user = await User.findById(req.user._id);
    if (!user) return res.status(404).json({ message: 'User not found' });

    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    // Fetch entries
    const entries = await Entry.find({
      user: user._id,
      date: { $gte: sevenDaysAgo }
    });

    const statsSummary = {
      workouts: entries.filter(e => e.type === 'workout').length,
      caloriesBurned: entries.filter(e => e.type === 'workout').reduce((sum, e) => sum + (e.caloriesBurned || 0), 0),
      meals: entries.filter(e => e.type === 'meal').length,
      caloriesConsumed: entries.filter(e => e.type === 'meal').reduce((sum, e) => sum + (e.caloriesConsumed || 0), 0),
      weights: entries.filter(e => e.type === 'weight').map(e => e.weightKg)
    };

    const systemPrompt = `You are a senior healthcare analyst on the HealthTrack Pro platform. 
Please write a weekly health progress analysis report in markdown format based on the user's logged activity over the past 7 days:

User Details:
Name: ${user.name}
Age: ${user.age}
Height: ${user.heightCm} cm
Weight: ${user.weightKg} kg

Last 7 Days Logged Stats:
- Workouts completed: ${statsSummary.workouts} (Total calories burned: ${statsSummary.caloriesBurned} kcal)
- Meals tracked: ${statsSummary.meals} (Total calories consumed: ${statsSummary.caloriesConsumed} kcal)
- Logged weight weights list: ${JSON.stringify(statsSummary.weights)}

Please provide:
1. Progress summary & key metrics analysis.
2. Positive highlights (habits done right).
3. Areas of improvement & warnings.
4. Concrete recommendations for the next 7 days.
Keep it encouraging, and end with the standard disclaimer that this report is AI-generated for general wellness purposes and should not be used as clinical diagnosis.`;

    const report = await callGemini(systemPrompt, false);
    res.json({ report });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
